### ISSUE TITLE
OIN voor identificatie

### ISSUE THREAD

**Issue by dmeijboom** [centrumvoorstandaarden/DigikoppelingRestfulApiProfiel#8]
In [Identificatie en authenticatie](https://logius.nl/sites/default/files/public/bestanden/diensten/DigiKoppeling/Standaarden/Digikoppeling-Identificatie-en-Authenticatie.pdf) lees ik dat het OIN kan worden uitgelezen uit het `serialNumber` veld van een certificaat. Dit is helder.

Wat ik mij echter afvraag is hoe dit werkt op het moment dat er een nieuw certificaat wordt uitgegeven voor een organisatie die al eerder een PKI Overheid certificaat had. Dit certificaat krijgt namelijk (als ik het goed begrijp) hetzelfde OIN dus hetzelfde `serialNumber`.

In [RFC5280](https://tools.ietf.org/rfc/rfc5280.txt) sectie `4.1.2.2` lees ik over het `serialNumber` echter het volgende:
```
It MUST be unique for each certificate issued by a given CA
```

Hier wordt volgens mij niet aan voldaan.

**Comment by hugoboos** [comment]
Het OIN staat in het `serialNumber` attribuut van het `Subject`, niet dat van het certificaat. Dit is dus geen probleem.
